"""Template definitions and rendering for GECK Generator."""

from datetime import datetime
from typing import Any

from jinja2 import Environment, BaseLoader, TemplateNotFound


# Main LLM_init.md template
LLM_INIT_TEMPLATE = """\
# Project: {{ project_name }}

**Repository:** {{ repo_url | default('Not specified', true) }}
**Local Path:** {{ local_path | default('Not specified', true) }}
**Created:** {{ created_date }}

## Goal

{{ goal }}

## Success Criteria

{% for criterion in success_criteria %}
- [ ] {{ criterion }}
{% endfor %}

## Constraints

- **Languages/Frameworks:** {{ languages | default('Not specified', true) }}
- **Must use:** {{ must_use | default('None specified', true) }}
- **Must avoid:** {{ must_avoid | default('None specified', true) }}
- **Target platforms:** {{ platforms | join(', ') if platforms else 'Not specified' }}

## Context

{{ context | default('No additional context provided.', true) }}

## Initial Task

{{ initial_task | default('Begin implementation based on the goal and success criteria above.', true) }}
"""

# Template for GECK folder README
GECK_README_TEMPLATE = """\
# LLM_GECK Folder

This folder contains GECK (Guided Engineering Configuration Kit) files for LLM-assisted development.

## Files

- `LLM_init.md` - Project initialization and goals
- `context.md` - Additional project context (optional)
- `history.md` - Session history log (optional)

## Usage

Point your LLM assistant to the `LLM_init.md` file to provide project context and goals.

Generated by GECK Generator v1.0
"""

# Template for context.md
CONTEXT_TEMPLATE = """\
# Project Context

## Architecture Overview

{{ architecture | default('*Describe the high-level architecture here.*', true) }}

## Key Files

{{ key_files | default('*List important files and their purposes here.*', true) }}

## Dependencies

{{ dependencies | default('*List major dependencies and their versions here.*', true) }}

## Notes

{{ notes | default('*Add any additional context or notes here.*', true) }}
"""

# Template for history.md
HISTORY_TEMPLATE = """\
# Session History

## {{ created_date }}

### Session Start

- Project: {{ project_name }}
- Goal: {{ goal | truncate(100) }}

---

*Add session notes and progress updates below.*
"""


class DictLoader(BaseLoader):
    """Jinja2 loader that loads templates from a dictionary."""

    def __init__(self, templates: dict[str, str]):
        self.templates = templates

    def get_source(self, environment: Environment, template: str) -> tuple[str, str, callable]:
        if template not in self.templates:
            raise TemplateNotFound(template)
        source = self.templates[template]
        return source, template, lambda: True


class TemplateEngine:
    """Jinja2-based template rendering engine."""

    # Built-in templates
    TEMPLATES = {
        "llm_init": LLM_INIT_TEMPLATE,
        "geck_readme": GECK_README_TEMPLATE,
        "context": CONTEXT_TEMPLATE,
        "history": HISTORY_TEMPLATE,
    }

    def __init__(self):
        """Initialize the template engine with built-in templates."""
        self.env = Environment(
            loader=DictLoader(self.TEMPLATES),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self._custom_templates: dict[str, str] = {}

    def render(self, template_name: str, variables: dict[str, Any]) -> str:
        """
        Render a template with the given variables.

        Args:
            template_name: Name of the template to render
            variables: Dictionary of variables to pass to the template

        Returns:
            Rendered template string
        """
        # Add default variables
        defaults = {
            "created_date": datetime.now().strftime("%Y-%m-%d"),
        }
        merged_vars = {**defaults, **variables}

        # Try custom templates first, then built-in
        if template_name in self._custom_templates:
            template = self.env.from_string(self._custom_templates[template_name])
        else:
            template = self.env.get_template(template_name)

        return template.render(**merged_vars)

    def render_string(self, template_string: str, variables: dict[str, Any]) -> str:
        """
        Render a template string directly.

        Args:
            template_string: Jinja2 template string
            variables: Dictionary of variables to pass to the template

        Returns:
            Rendered template string
        """
        defaults = {
            "created_date": datetime.now().strftime("%Y-%m-%d"),
        }
        merged_vars = {**defaults, **variables}

        template = self.env.from_string(template_string)
        return template.render(**merged_vars)

    def list_templates(self) -> list[str]:
        """
        List all available template names.

        Returns:
            List of template names
        """
        built_in = list(self.TEMPLATES.keys())
        custom = list(self._custom_templates.keys())
        return built_in + custom

    def add_template(self, name: str, template_string: str) -> None:
        """
        Add a custom template.

        Args:
            name: Name for the template
            template_string: Jinja2 template string
        """
        self._custom_templates[name] = template_string

    def load_template_from_file(self, name: str, filepath: str) -> None:
        """
        Load a custom template from a file.

        Args:
            name: Name for the template
            filepath: Path to the template file
        """
        with open(filepath, "r", encoding="utf-8") as f:
            template_string = f.read()
        self.add_template(name, template_string)
